version: '3.9'
services:
  pg:
    image: 'postgres:15'
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    environment:
      - PGPORT=${PGPORT}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSERNAME}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
